// <auto-generated />
using System;
using HRMSolution.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRMSolution.Data.Migrations
{
    [DbContext(typeof(HRMDbContext))]
    [Migration("20211005081159_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucChucDanh", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("maChucDanh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float>("phuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("tenChucDanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucChucDanh");

                    b.HasData(
                        new
                        {
                            id = 1,
                            maChucDanh = "CD01",
                            phuCap = 100000f,
                            tenChucDanh = "Cử Nhân"
                        },
                        new
                        {
                            id = 2,
                            maChucDanh = "CD02",
                            phuCap = 200000f,
                            tenChucDanh = "Thạc Sĩ"
                        },
                        new
                        {
                            id = 3,
                            maChucDanh = "CD03",
                            phuCap = 300000f,
                            tenChucDanh = "Tiến Sĩ"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucChucVu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("maChucVu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float>("phuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("tenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucChucVu");

                    b.HasData(
                        new
                        {
                            id = 1,
                            maChucVu = "CV01",
                            phuCap = 100000f,
                            tenChucVu = "Nhân viên"
                        },
                        new
                        {
                            id = 2,
                            maChucVu = "CV02",
                            phuCap = 200000f,
                            tenChucVu = "Trưởng Phòng"
                        },
                        new
                        {
                            id = 3,
                            maChucVu = "CV03",
                            phuCap = 300000f,
                            tenChucVu = "Giám Đốc"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucChuyenMon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("maChuyenMon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tenChuyenMon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucChuyenMon");

                    b.HasData(
                        new
                        {
                            id = 1,
                            maChuyenMon = "CM01",
                            tenChuyenMon = "Tài chính – ngân hàng"
                        },
                        new
                        {
                            id = 2,
                            maChuyenMon = "CM02",
                            tenChuyenMon = "Hành chính văn phòng"
                        },
                        new
                        {
                            id = 3,
                            maChuyenMon = "CM03",
                            tenChuyenMon = "Quản tị kinh doanh"
                        },
                        new
                        {
                            id = 4,
                            maChuyenMon = "CM04",
                            tenChuyenMon = "Kế toán – kiểm toán"
                        },
                        new
                        {
                            id = 5,
                            maChuyenMon = "CM05",
                            tenChuyenMon = "Kinh Tế"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucDanToc", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucDanToc");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenDanhMuc = "kinh"
                        },
                        new
                        {
                            id = 2,
                            tenDanhMuc = "Mông"
                        },
                        new
                        {
                            id = 3,
                            tenDanhMuc = "Thái"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucHonNhan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucHonNhan");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenDanhMuc = "Độc Thân"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucKhenThuongKyLuat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucKhenThuongKyLuat");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenDanhMuc = "Thưởng Nhân viên suất xác tháng"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucLoaiHopDong", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("maLoaiHopDong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tenLoaiHopDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucLoaiHopDong");

                    b.HasData(
                        new
                        {
                            id = 1,
                            maLoaiHopDong = "MHD01",
                            tenLoaiHopDong = "Hợp đồng một năm"
                        },
                        new
                        {
                            id = 2,
                            maLoaiHopDong = "MHD02",
                            tenLoaiHopDong = "Hợp đồng ba năm"
                        },
                        new
                        {
                            id = 3,
                            maLoaiHopDong = "MHD03",
                            tenLoaiHopDong = "Hợp đồng vô thời hạn"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucNgachCongChuc", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenNgach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucNgachCongChuc");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenNgach = "Loại A"
                        },
                        new
                        {
                            id = 2,
                            tenNgach = "Loại B"
                        },
                        new
                        {
                            id = 3,
                            tenNgach = "Loại C"
                        },
                        new
                        {
                            id = 4,
                            tenNgach = "Loại D"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucNgoaiNgu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucNgoaiNgu");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenDanhMuc = "Tiếng Anh"
                        },
                        new
                        {
                            id = 2,
                            tenDanhMuc = "Tiếng Trung Quốc"
                        },
                        new
                        {
                            id = 3,
                            tenDanhMuc = "Tiếng pháp"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucNguoiThan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucNguoiThan");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenDanhMuc = "Bố"
                        },
                        new
                        {
                            id = 2,
                            tenDanhMuc = "Mẹ"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucPhongBan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("maPhongBan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tenPhongBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucPhongBan");

                    b.HasData(
                        new
                        {
                            id = 1,
                            maPhongBan = "PB01",
                            tenPhongBan = "1"
                        },
                        new
                        {
                            id = 2,
                            maPhongBan = "PB02",
                            tenPhongBan = "2"
                        },
                        new
                        {
                            id = 3,
                            maPhongBan = "PB03",
                            tenPhongBan = "3"
                        },
                        new
                        {
                            id = 4,
                            maPhongBan = "PB04",
                            tenPhongBan = "4"
                        },
                        new
                        {
                            id = 5,
                            maPhongBan = "PB05",
                            tenPhongBan = "5"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucTinhChatLaoDong", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenTinhChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("danhMucTinhChatLaoDongs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenTinhChat = "Chính thức"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucTo", b =>
                {
                    b.Property<int>("idTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idPhongBan")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<string>("maTo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tenTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTo");

                    b.HasIndex("idPhongBan");

                    b.ToTable("DanhMucTo");

                    b.HasData(
                        new
                        {
                            idTo = 1,
                            idPhongBan = 1,
                            maTo = "T01",
                            tenTo = "Tổ 1"
                        },
                        new
                        {
                            idTo = 2,
                            idPhongBan = 1,
                            maTo = "T02",
                            tenTo = "Tổ 1"
                        },
                        new
                        {
                            idTo = 3,
                            idPhongBan = 1,
                            maTo = "T03",
                            tenTo = "Tổ 2"
                        },
                        new
                        {
                            idTo = 4,
                            idPhongBan = 1,
                            maTo = "T04",
                            tenTo = "Tổ 3"
                        },
                        new
                        {
                            idTo = 5,
                            idPhongBan = 1,
                            maTo = "T05",
                            tenTo = "Tổ 4"
                        },
                        new
                        {
                            idTo = 6,
                            idPhongBan = 2,
                            maTo = "T06",
                            tenTo = "Tổ 5"
                        },
                        new
                        {
                            idTo = 7,
                            idPhongBan = 2,
                            maTo = "T06",
                            tenTo = "Tổ 6"
                        },
                        new
                        {
                            idTo = 8,
                            idPhongBan = 2,
                            maTo = "T07",
                            tenTo = "Tổ 7"
                        },
                        new
                        {
                            idTo = 9,
                            idPhongBan = 2,
                            maTo = "T08",
                            tenTo = "Tổ 8"
                        },
                        new
                        {
                            idTo = 10,
                            idPhongBan = 3,
                            maTo = "T09",
                            tenTo = "Tổ 9"
                        },
                        new
                        {
                            idTo = 11,
                            idPhongBan = 3,
                            maTo = "T010",
                            tenTo = "Tổ 10"
                        },
                        new
                        {
                            idTo = 12,
                            idPhongBan = 3,
                            maTo = "T011",
                            tenTo = "Tổ 11"
                        },
                        new
                        {
                            idTo = 13,
                            idPhongBan = 3,
                            maTo = "T012",
                            tenTo = "Tổ 12"
                        },
                        new
                        {
                            idTo = 14,
                            idPhongBan = 4,
                            maTo = "T013",
                            tenTo = "Tổ 13"
                        },
                        new
                        {
                            idTo = 15,
                            idPhongBan = 4,
                            maTo = "T014",
                            tenTo = "Tổ 14"
                        },
                        new
                        {
                            idTo = 16,
                            idPhongBan = 4,
                            maTo = "T015",
                            tenTo = "Tổ 15"
                        },
                        new
                        {
                            idTo = 17,
                            idPhongBan = 4,
                            maTo = "T016",
                            tenTo = "Tổ 16"
                        },
                        new
                        {
                            idTo = 18,
                            idPhongBan = 5,
                            maTo = "T017",
                            tenTo = "Tổ 17"
                        },
                        new
                        {
                            idTo = 19,
                            idPhongBan = 5,
                            maTo = "T018",
                            tenTo = "Tổ 18"
                        },
                        new
                        {
                            idTo = 20,
                            idPhongBan = 5,
                            maTo = "T019",
                            tenTo = "Tổ 19"
                        },
                        new
                        {
                            idTo = 21,
                            idPhongBan = 5,
                            maTo = "T020",
                            tenTo = "Tổ 20"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucTonGiao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucTonGiao");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenDanhMuc = "không"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucTrinhDo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenTrinhDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("DanhMucTrinhDo");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenTrinhDo = "Giỏi"
                        },
                        new
                        {
                            id = 2,
                            tenTrinhDo = "Khá"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DieuChuyen", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("chiTiet")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("idChucVu")
                        .HasColumnType("int");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ngayHieuLuc")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("phong")
                        .HasColumnType("int");

                    b.Property<int>("to")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idChucVu");

                    b.HasIndex("maNhanVien");

                    b.ToTable("DieuChuyen");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.HinhThucDaoTao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenHinhThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("HinhThucDaoTao");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenHinhThuc = "Đại học"
                        },
                        new
                        {
                            id = 2,
                            tenHinhThuc = "Cao đẳng"
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.HopDong", b =>
                {
                    b.Property<string>("maHopDong")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ghiChu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("hopDongDenNgay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("hopDongTuNgay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("idChucDanh")
                        .HasColumnType("int");

                    b.Property<int>("idLoaiHopDong")
                        .HasColumnType("int");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("maHopDong");

                    b.HasIndex("idChucDanh");

                    b.HasIndex("idLoaiHopDong");

                    b.HasIndex("maNhanVien");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.KhenThuongKyLuat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idDanhMucKhenThuong")
                        .HasColumnType("int");

                    b.Property<bool?>("loai")
                        .HasColumnType("bit");

                    b.Property<string>("lyDo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("noiDung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("idDanhMucKhenThuong");

                    b.HasIndex("maNhanVien");

                    b.ToTable("KhenThuongKyLuat");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.LichSu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("hanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ngayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("thaoTac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("LichSu");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.LichSuBanThan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("biBatDiTu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("thamGiaChinhTri")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("thanNhanNuocNgoai")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.HasIndex("maNhanVien")
                        .IsUnique();

                    b.ToTable("LichSuBanThan");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.LienHeKhanCap", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("dienThoai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("quanHe")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("maNhanVien")
                        .IsUnique();

                    b.ToTable("LienHeKhanCap");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.Luong", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bacLuong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ghiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float?>("heSoLuong")
                        .HasColumnType("real");

                    b.Property<float?>("luongCoBan")
                        .HasColumnType("real");

                    b.Property<string>("maHopDong")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ngayHieuLuc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayKetThuc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int?>("nhomLuong")
                        .HasColumnType("int");

                    b.Property<float?>("phuCapKhac")
                        .HasColumnType("real");

                    b.Property<float?>("phuCapTrachNhiem")
                        .HasColumnType("real");

                    b.Property<string>("thoiHanLenLuong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float?>("tongLuong")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("maHopDong");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.NgoaiNgu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idDanhMucNgoaiNgu")
                        .HasColumnType("int");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ngayCap")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("noiCap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("trinhDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("idDanhMucNgoaiNgu");

                    b.HasIndex("maNhanVien");

                    b.ToTable("NgoaiNgu");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.NguoiThan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("dienThoai")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool?>("gioiTinh")
                        .HasColumnType("bit");

                    b.Property<int>("idDanhMucNguoiThan")
                        .HasColumnType("int");

                    b.Property<string>("khac")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ngaySinh")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("ngheNghiep")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("quanHe")
                        .HasColumnType("int");

                    b.Property<string>("tenNguoiThan")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("id");

                    b.HasIndex("idDanhMucNguoiThan");

                    b.HasIndex("maNhanVien");

                    b.ToTable("NguoiThan");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.NhanVien", b =>
                {
                    b.Property<string>("maNhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("anh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("atm")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("bhxh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("bhyt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("cccd")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("chucVuHienTai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("coQuanTuyenDung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("conChinhSach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("congViecChinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("danhHieuCaoNhat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("diDong")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("dienThoai")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("dienThoaiKhac")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("facebook")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("gioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("hoChieu")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("idDanToc")
                        .HasColumnType("int");

                    b.Property<int>("idDanhMucHonNhan")
                        .HasColumnType("int");

                    b.Property<int>("idNgachCongChuc")
                        .HasColumnType("int");

                    b.Property<int>("idPhongBan")
                        .HasColumnType("int");

                    b.Property<int>("idTonGiao")
                        .HasColumnType("int");

                    b.Property<bool?>("laConChinhSach")
                        .HasColumnType("bit");

                    b.Property<bool?>("laThuongBinh")
                        .HasColumnType("bit");

                    b.Property<string>("lyDoNghiViec")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("maSoThue")
                        .HasColumnType("int");

                    b.Property<string>("ngachCongChucNoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nganHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ngayCapCCCD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayCapHoChieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayChinhThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("ngayHetHanCCCD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayHetHanHoChieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayNghiViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayNhapNgu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("ngaySinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayThuViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayTuyenDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayVaoBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayVaoDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayVaoDangChinhThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayVaoDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ngayXuatNgu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("ngheNghiep")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("noiCapCCCD")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("noiCapHoChieu")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("noiSinh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("noiThamGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("quanHamCaoNhat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("queQuan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("quocTich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("skype")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("tamTru")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("thuongBinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("thuongTru")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("tinhChatLaoDong")
                        .HasColumnType("int");

                    b.Property<int>("to")
                        .HasColumnType("int");

                    b.Property<bool?>("trangThaiLaoDong")
                        .HasColumnType("bit");

                    b.HasKey("maNhanVien");

                    b.HasIndex("idDanToc");

                    b.HasIndex("idDanhMucHonNhan");

                    b.HasIndex("idNgachCongChuc");

                    b.HasIndex("idPhongBan");

                    b.HasIndex("idTonGiao");

                    b.HasIndex("tinhChatLaoDong");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            maNhanVien = "NV0001",
                            anh = "1",
                            cccd = "040828462",
                            chucVuHienTai = "Nhân Viên",
                            coQuanTuyenDung = "Phát Đạt",
                            congViecChinh = "code",
                            diDong = "0961441404",
                            dienThoai = "02466666",
                            gioiTinh = true,
                            hoTen = "Đào Ngọc Hưởng",
                            idDanToc = 1,
                            idDanhMucHonNhan = 1,
                            idNgachCongChuc = 1,
                            idPhongBan = 1,
                            idTonGiao = 1,
                            ngayCapCCCD = new DateTime(2012, 3, 21, 13, 26, 0, 0, DateTimeKind.Unspecified),
                            ngayHetHanCCCD = new DateTime(2012, 3, 21, 13, 26, 0, 0, DateTimeKind.Unspecified),
                            ngaySinh = new DateTime(1998, 3, 21, 13, 26, 0, 0, DateTimeKind.Unspecified),
                            ngheNghiep = "Sinh viên",
                            noiCapCCCD = "Điện Biên",
                            noiSinh = "Hưng Yên",
                            queQuan = "Hưng Yên",
                            quocTich = "Việt Nam",
                            tamTru = "Đại học FPT",
                            thuongTru = "Điện Biên",
                            tinhChatLaoDong = 1,
                            to = 1
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.TaiKhoan", b =>
                {
                    b.Property<string>("tenDangNhap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("vaiTro")
                        .HasColumnType("int");

                    b.HasKey("tenDangNhap");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            tenDangNhap = "admin",
                            matKhau = "123",
                            vaiTro = 1
                        });
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.TrinhDoVanHoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("denThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("idChuyenMon")
                        .HasColumnType("int");

                    b.Property<int>("idHinhThucDaoTao")
                        .HasColumnType("int");

                    b.Property<int>("idTrinhDo")
                        .HasColumnType("int");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tenTruong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("tuThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("id");

                    b.HasIndex("idChuyenMon");

                    b.HasIndex("idHinhThucDaoTao");

                    b.HasIndex("idTrinhDo");

                    b.HasIndex("maNhanVien");

                    b.ToTable("TrinhDoVanHoa");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.YTe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("benhTat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float?>("canNang")
                        .HasColumnType("real");

                    b.Property<float?>("chieuCao")
                        .HasColumnType("real");

                    b.Property<bool?>("khuyetTat")
                        .HasColumnType("bit");

                    b.Property<string>("luuY")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("maNhanVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("nhomMau")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("tinhTrangSucKhoe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("maNhanVien")
                        .IsUnique();

                    b.ToTable("YTe");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucTo", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.DanhMucPhongBan", "DanhMucPhongBan")
                        .WithMany("DanhMucTos")
                        .HasForeignKey("idPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucPhongBan");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DieuChuyen", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.DanhMucChucVu", "DanhMucChucVu")
                        .WithMany("DieuChuyens")
                        .HasForeignKey("idChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("DieuChuyens")
                        .HasForeignKey("maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucChucVu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.HopDong", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.DanhMucChucDanh", "DanhMucChucDanh")
                        .WithMany("HopDongs")
                        .HasForeignKey("idChucDanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.DanhMucLoaiHopDong", "DanhMucLoaiHopDong")
                        .WithMany("HopDongs")
                        .HasForeignKey("idLoaiHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("HopDongs")
                        .HasForeignKey("maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucChucDanh");

                    b.Navigation("DanhMucLoaiHopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.KhenThuongKyLuat", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.DanhMucKhenThuongKyLuat", "DanhMucKhenThuongKyLuat")
                        .WithMany("KhenThuongKyLuats")
                        .HasForeignKey("idDanhMucKhenThuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("KhenThuongKyLuats")
                        .HasForeignKey("maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucKhenThuongKyLuat");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.LichSuBanThan", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithOne("LichSuBanThan")
                        .HasForeignKey("HRMSolution.Data.Entities.LichSuBanThan", "maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.LienHeKhanCap", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithOne("LienHeKhanCap")
                        .HasForeignKey("HRMSolution.Data.Entities.LienHeKhanCap", "maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.Luong", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.HopDong", "HopDong")
                        .WithMany("Luongs")
                        .HasForeignKey("maHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.NgoaiNgu", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.DanhMucNgoaiNgu", "DanhMucNgoaiNgu")
                        .WithMany("NgoaiNgus")
                        .HasForeignKey("idDanhMucNgoaiNgu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("NgoaiNgus")
                        .HasForeignKey("maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucNgoaiNgu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.NguoiThan", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.DanhMucNguoiThan", "DanhMucNguoiThan")
                        .WithMany("NguoiThans")
                        .HasForeignKey("idDanhMucNguoiThan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("NguoiThans")
                        .HasForeignKey("maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucNguoiThan");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.NhanVien", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.DanhMucDanToc", "DanhMucDanToc")
                        .WithMany("NhanViens")
                        .HasForeignKey("idDanToc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.DanhMucHonNhan", "DanhMucHonNhan")
                        .WithMany("NhanViens")
                        .HasForeignKey("idDanhMucHonNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.DanhMucNgachCongChuc", "DanhMucNgachCongChuc")
                        .WithMany("NhanViens")
                        .HasForeignKey("idNgachCongChuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.DanhMucPhongBan", "DanhMucPhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("idPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.DanhMucTonGiao", "DanhMucTonGiao")
                        .WithMany("NhanViens")
                        .HasForeignKey("idTonGiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.DanhMucTinhChatLaoDong", "DanhMucTinhChatLaoDong")
                        .WithMany("NhanViens")
                        .HasForeignKey("tinhChatLaoDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucDanToc");

                    b.Navigation("DanhMucHonNhan");

                    b.Navigation("DanhMucNgachCongChuc");

                    b.Navigation("DanhMucPhongBan");

                    b.Navigation("DanhMucTinhChatLaoDong");

                    b.Navigation("DanhMucTonGiao");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.TrinhDoVanHoa", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.DanhMucChuyenMon", "DanhMucChuyenMon")
                        .WithMany("TrinhDoVanHoas")
                        .HasForeignKey("idChuyenMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.HinhThucDaoTao", "HinhThucDaoTao")
                        .WithMany("TrinhDoVanHoas")
                        .HasForeignKey("idHinhThucDaoTao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.DanhMucTrinhDo", "DanhMucTrinhDo")
                        .WithMany("TrinhDoVanHoas")
                        .HasForeignKey("idTrinhDo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("TrinhDoVanHoas")
                        .HasForeignKey("maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucChuyenMon");

                    b.Navigation("DanhMucTrinhDo");

                    b.Navigation("HinhThucDaoTao");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.YTe", b =>
                {
                    b.HasOne("HRMSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithOne("YTe")
                        .HasForeignKey("HRMSolution.Data.Entities.YTe", "maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucChucDanh", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucChucVu", b =>
                {
                    b.Navigation("DieuChuyens");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucChuyenMon", b =>
                {
                    b.Navigation("TrinhDoVanHoas");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucDanToc", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucHonNhan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucKhenThuongKyLuat", b =>
                {
                    b.Navigation("KhenThuongKyLuats");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucLoaiHopDong", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucNgachCongChuc", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucNgoaiNgu", b =>
                {
                    b.Navigation("NgoaiNgus");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucNguoiThan", b =>
                {
                    b.Navigation("NguoiThans");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucPhongBan", b =>
                {
                    b.Navigation("DanhMucTos");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucTinhChatLaoDong", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucTonGiao", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.DanhMucTrinhDo", b =>
                {
                    b.Navigation("TrinhDoVanHoas");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.HinhThucDaoTao", b =>
                {
                    b.Navigation("TrinhDoVanHoas");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.HopDong", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("HRMSolution.Data.Entities.NhanVien", b =>
                {
                    b.Navigation("DieuChuyens");

                    b.Navigation("HopDongs");

                    b.Navigation("KhenThuongKyLuats");

                    b.Navigation("LichSuBanThan");

                    b.Navigation("LienHeKhanCap");

                    b.Navigation("NgoaiNgus");

                    b.Navigation("NguoiThans");

                    b.Navigation("TrinhDoVanHoas");

                    b.Navigation("YTe");
                });
#pragma warning restore 612, 618
        }
    }
}
